version: "3.4"
services:
  kort:
    container_name: kort
    restart: always
    build: .
    ports:
      - "3000:3000"
    # this makes sure mongo is up before kort starts, apparently this feature may be removed in tbe future
    # https://docs.docker.com/compose/compose-file/#links
    links:
      - mongo
    # https://stackoverflow.com/questions/40873165/use-docker-run-command-to-pass-arguments-to-cmd-in-dockerfile
    environment:
      - mongoHost=mongo
      # Set admin and admin password for the app here if you want to use environment variables
    # https://docs.docker.com/compose/compose-file/#healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 3s
    env_file:
      - .env

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
