# validate YAML
# https://codebeautify.org/yaml-validator

name: Build and Test
on: [push, pull_request]

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      # https://github.com/actions/setup-node/
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # https://github.com/marketplace/actions/mongodb-in-github-actions
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
      - run: npm install
      # ampersand means run in the background
      # sleep and wait for the app to load
      # start running casperjs tests
      - run: node app.js &
      - run: sleep 6
      - run: npm test
